# Auto-update src/version.js with a short build version (YYMMDD-##), reset daily (LOCAL TIME)
# - Counts commits between local midnight and next midnight (not UTC)
# - Writes only the small version string, e.g., 250815-01
$ErrorActionPreference = "Stop"

$root = (git rev-parse --show-toplevel).Trim()
$versionFile = Join-Path $root 'src/version.js'

# Local date part YYMMDD
$datePart = (Get-Date).ToString('yyMMdd')

# Local midnight range
$start = Get-Date -Hour 0 -Minute 0 -Second 0
$end = $start.AddDays(1)

# Format as ISO for git's --since/--until
$since = $start.ToString('yyyy-MM-ddTHH:mm:ss')
$until = $end.ToString('yyyy-MM-ddTHH:mm:ss')

# Count commits made today on the current branch
# (If you want to exclude merges, add --no-merges)
$todayCommits = (git log --since="$since" --until="$until" --pretty=format:"%h" 2>$null | Measure-Object).Count
$counter = '{0:D2}' -f ($todayCommits + 1)

$ver = "$datePart-$counter"

$js = @"
// this file is auto-generated by .githooks/pre-commit.ps1
export const BUILD_VERSION = '$ver';
"@

# Write file (UTF-8, LF). Simple write is fine here; changing every commit is expected.
Set-Content -Path $versionFile -Value $js -NoNewline -Encoding UTF8

# Stage for commit
git add -- "src/version.js"
