# Auto-update src/version.js with a UTC timestamp (yyyyMMdd-HHmmss)
$ErrorActionPreference = "Stop"

$root = git rev-parse --show-toplevel
$versionFile = Join-Path $root "src\version.js"

$ts = (Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss")
# If you want to include previous short SHA too:
# $sha = (git rev-parse --short HEAD) 2>$null
# $ver = if ($LASTEXITCODE -eq 0) { "$ts-$sha" } else { $ts }
$ver = $ts

$js = @"
// this file is auto-generated by .githooks/pre-commit.ps1
export const BUILD_VERSION = '$ver';
"@

Set-Content -Path $versionFile -Value $js -NoNewline -Encoding UTF8
git add "src/version.js"
